/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiConvertMp4RouteImport } from './routes/api/convert-mp4'
import { Route as ApiMediaProxyRouteImport } from './routes/api/media-proxy'
import { Route as ApiMediaSearchRouteImport } from './routes/api/media-search'
import { Route as ApiMusicSearchRouteImport } from './routes/api/music-search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConvertMp4Route = ApiConvertMp4RouteImport.update({
  id: '/api/convert-mp4',
  path: '/api/convert-mp4',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaProxyRoute = ApiMediaProxyRouteImport.update({
  id: '/api/media-proxy',
  path: '/api/media-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSearchRoute = ApiMediaSearchRouteImport.update({
  id: '/api/media-search',
  path: '/api/media-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMusicSearchRoute = ApiMusicSearchRouteImport.update({
  id: '/api/music-search',
  path: '/api/music-search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/convert-mp4': typeof ApiConvertMp4Route
  '/api/media-proxy': typeof ApiMediaProxyRoute
  '/api/media-search': typeof ApiMediaSearchRoute
  '/api/music-search': typeof ApiMusicSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/convert-mp4': typeof ApiConvertMp4Route
  '/api/media-proxy': typeof ApiMediaProxyRoute
  '/api/media-search': typeof ApiMediaSearchRoute
  '/api/music-search': typeof ApiMusicSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/convert-mp4': typeof ApiConvertMp4Route
  '/api/media-proxy': typeof ApiMediaProxyRoute
  '/api/media-search': typeof ApiMediaSearchRoute
  '/api/music-search': typeof ApiMusicSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/convert-mp4'
    | '/api/media-proxy'
    | '/api/media-search'
    | '/api/music-search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/convert-mp4'
    | '/api/media-proxy'
    | '/api/media-search'
    | '/api/music-search'
  id:
    | '__root__'
    | '/'
    | '/api/convert-mp4'
    | '/api/media-proxy'
    | '/api/media-search'
    | '/api/music-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiConvertMp4Route: typeof ApiConvertMp4Route
  ApiMediaProxyRoute: typeof ApiMediaProxyRoute
  ApiMediaSearchRoute: typeof ApiMediaSearchRoute
  ApiMusicSearchRoute: typeof ApiMusicSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/convert-mp4': {
      id: '/api/convert-mp4'
      path: '/api/convert-mp4'
      fullPath: '/api/convert-mp4'
      preLoaderRoute: typeof ApiConvertMp4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media-proxy': {
      id: '/api/media-proxy'
      path: '/api/media-proxy'
      fullPath: '/api/media-proxy'
      preLoaderRoute: typeof ApiMediaProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media-search': {
      id: '/api/media-search'
      path: '/api/media-search'
      fullPath: '/api/media-search'
      preLoaderRoute: typeof ApiMediaSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/music-search': {
      id: '/api/music-search'
      path: '/api/music-search'
      fullPath: '/api/music-search'
      preLoaderRoute: typeof ApiMusicSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiConvertMp4Route: ApiConvertMp4Route,
  ApiMediaProxyRoute: ApiMediaProxyRoute,
  ApiMediaSearchRoute: ApiMediaSearchRoute,
  ApiMusicSearchRoute: ApiMusicSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
